# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 22, host: 33312
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 768
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl start docker

    docker pull nginx:stable
    docker run -d -p 80:80 --name http-server-nocompose nginx:stable

    if [ ! -e /mnt/containers/web-frontend ]; then
      mkdir -p /mnt/containers/web-frontend
      echo "version: '3.4'
services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 8080:8080" >> /mnt/containers/web-frontend/docker-compose.yml
      docker compose -f /mnt/containers/web-frontend/docker-compose.yml up -d
    fi

    if [ ! -e /mnt/test.img ]; then
      truncate -s 256M /mnt/test.img
      losetup /dev/loop0 /mnt/test.img
      pvcreate /dev/loop0
      vgcreate test_vg /dev/loop0
      lvcreate -L 128M -n test_lv test_vg
    fi
  SHELL
end
