# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 22, host: 33312
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 768
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl start docker

    truncate -s 256M /mnt/test.img
    losetup /dev/loop0 /mnt/test.img
    pvcreate /dev/loop0
    vgcreate test_vg /dev/loop0
    lvcreate -L 128M -n test_lv test_vg

    docker pull nginx:stable
    docker run -d -p 80:80 --name http-server nginx:stable
  SHELL
end
