# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.network "forwarded_port", guest: 22, host: 33351
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 768
  end
  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -e /mnt/test.img ]; then
      DEBIAN_FRONTEND=noninteractive apk add lvm2
      truncate -s 256M /mnt/test.img
      losetup /dev/loop0 /mnt/test.img
      pvcreate /dev/loop0
      vgcreate test_vg /dev/loop0
      lvcreate -L 128M -n test_lv test_vg
    else 
      losetup /dev/loop0 /mnt/test.img
    fi

  SHELL
end
