preferences:
  use_sandbox_mode: true
  refresh_hosts_on_start: false
  use_remote_editor: true
  sudo_remote_editor: true
  remote_text_editor: nano
  text_editor: internal
  terminal: internal
  terminal_args: []
  close_to_tray: true
  show_monitor_notifications: true
  show_charts: false
  show_chart_threshold_lines: true
  editor_preferences:
    edit_mode: regular
    font_size: 12
    word_wrap: true
  saved_core_addresses: []
display_options:
  qtquick_style: ''
  hide_info_notifications: false
  show_status_bar: true
  main_view_split_ratio: 0.8
schema_version: 8
